# Generated by Django 3.2.15 on 2022-08-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_id', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('img', models.FileField(upload_to='')),
                ('suspeito', models.BinaryField()),
            ],
        ),
    ]
