# Generated by Django 3.2.15 on 2022-08-11 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_id', '0002_face'),
    ]

    operations = [
        migrations.RenameField(
            model_name='face',
            old_name='nome',
            new_name='name',
        ),
    ]
