# Generated by Django 3.2.15 on 2022-08-11 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_id', '0003_rename_nome_face_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
    ]
